version: '3.8'

services:
  test-db:
    image: mysql:8.0
    container_name: test-mysql
    environment:
      MYSQL_ROOT_PASSWORD: testroot
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: fastapi_test
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-ptestroot"]
      interval: 5s
      timeout: 10s
      retries: 10

  test-app:
    build: .
    container_name: test-fastapi
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      TEST_DATABASE_URL: "mysql+pymysql://testuser:testpass@test-db:3306/fastapi_test"
    depends_on:
      test-db:
        condition: service_healthy
    command: [
      "sh", "-c",
      "./scripts/wait-for-db.sh test-db -- pytest -v tests/"
    ]
    volumes:
      - .:/app