# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "8000:8000"
#     environment:
#       - DATABASE_URL=mysql+pymysql://test_user:test_password@mysql:3306/test_db
#     depends_on:
#       mysql:
#         condition: service_healthy

#   mysql:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: test_db
#       MYSQL_USER: test_user
#       MYSQL_PASSWORD: test_password
#     ports:
#       - "3306:3306"
#     volumes:
#       - ./sql_scripts:/docker-entrypoint-initdb.d
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'testpassword'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
    # volumes:
    #   - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  mysql-data:  