name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ptestpass -u testuser"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        volumes:
          - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    # 等待 MySQL 服务启动
    - name: Wait for MySQL
      run: sleep 15

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest mysql-connector-python

    - name: Run tests
      env:
        MYSQL_HOST: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_USER: testuser
        MYSQL_PASSWORD: testpass
        MYSQL_DATABASE: testdb
      run: |
        pytest -v tests/

    - name: Build Docker image
      run: docker build -t fastapi-mysql-app .

    - name: Test Docker container
      run: |
        docker run -d \
          --name fastapi-test \
          -p 8000:8000 \
          -e MYSQL_HOST=host.docker.internal \
          fastapi-mysql-app
        
        # 等待服务启动
        sleep 10
        
        # 测试API端点
        curl -s -X GET http://localhost:8000/ | grep 'Welcome'
        curl -s -X GET http://localhost:8000/items/1 | grep 'Item'